on:
    push:
      branches: [main, dev]
    pull_request:
      branches: [main, dev]
    paths:
    - 'frontend/**'
  
jobs:
  build-frontend: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test


  
  
  